<?php

/**
 * BasePageContentImages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $content_id
 * @property enum $type
 * @property string $image_small
 * @property string $image
 * @property string $titre
 * @property PageContent $PageContent
 * 
 * @method integer           getContentId()   Returns the current record's "content_id" value
 * @method enum              getType()        Returns the current record's "type" value
 * @method string            getImageSmall()  Returns the current record's "image_small" value
 * @method string            getImage()       Returns the current record's "image" value
 * @method string            getTitre()       Returns the current record's "titre" value
 * @method PageContent       getPageContent() Returns the current record's "PageContent" value
 * @method PageContentImages setContentId()   Sets the current record's "content_id" value
 * @method PageContentImages setType()        Sets the current record's "type" value
 * @method PageContentImages setImageSmall()  Sets the current record's "image_small" value
 * @method PageContentImages setImage()       Sets the current record's "image" value
 * @method PageContentImages setTitre()       Sets the current record's "titre" value
 * @method PageContentImages setPageContent() Sets the current record's "PageContent" value
 * 
 * @package    moondo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePageContentImages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page_content_images');
        $this->hasColumn('content_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'image',
              1 => 'video',
             ),
             'notnull' => true,
             'default' => 'image',
             ));
        $this->hasColumn('image_small', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('titre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('orderBy', 'position');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PageContent', array(
             'local' => 'content_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'content_id',
             ),
             ));
        $this->actAs($sortable0);
    }
}