<?php

/**
 * PluginPageContentLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageContentLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageContentLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageContentLink');
    }
}