<?php

/**
 * PluginPageContentDocTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageContentDocTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageContentDocTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageContentDoc');
    }
}