<?php

/**
 * PluginPageContentImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageContentImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageContentImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageContentImage');
    }
}