<?php

/**
 * PluginPageContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageContent');
    }
	
	public static function getVisible($page_id, $users='tots') {
		$q = PageContentTable::getInstance()
			->createQuery()
			->where('page_id = ?', $page_id)
			->andWhere('visible = ?', true);
		if ($users!='tots') $q->andWhere('users = ? OR users = ?',array($users, 'tots'));
		else $q->andWhere('users = ?', $users);
		return $q->execute();
	}
}