<?php

/**
 * PluginPageContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPageContent extends BasePageContent
{
	public function getFormattedText() {
		$utilisateur = '';
		$sf_user = sfContext::getInstance()->getUser();
		if ($sf_user->isAuthenticated()) {
			$utilisateur= ' '.$sf_user->getGuardUser()->getFirstName().' '.$sf_user->getGuardUser()->getLastName();
		}
		$slugs = array(
			'/%usuari%/',
		);
		$values = array(
			$utilisateur,
		);
		$dbpages = PageTable::getInstance()->findAll();
		$pages = array();
		foreach($dbpages as $p) {
			$slugs[] = '/href="_'.$p->id.'"/';
			if ($p->visible) $values[] = 'href="'.$p->getUrl().'" title="'.addslashes($p->titre).'"';
			else $values[] = 'href=""';
		}
		return preg_replace($slugs, $values, $this->getText() );
	}
	
	public function getFormattedTextForAdmin() {
		$slugs = array();
		$values = array();
		$dbpages = PageTable::getInstance()->findAll();
		$pages = array();
		foreach($dbpages as $p) {
			$slugs[] = '/href="_'.$p->id.'"/';
			$url = sfProjectConfiguration::getActive()->generateBackendUrl('cms_admin_page_edit',array('sf_subject'=>$p));
			$values[] = 'href="'.$url.'" title="'.addslashes($p->titre).'"';
		}
		return preg_replace($slugs, $values, $this->text );
	}
	
    public function preDelete($event)
    {
		foreach($this->getDocs() as $doc) {
			$doc->preDelete($event);
		}
		foreach($this->getImages() as $image) {
			$image->preDelete($event);
		}
		parent::preDelete($event);		
	}
	

}