<?php

/**
 * PluginPageContentVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageContentVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageContentVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageContentVideo');
    }
}