<?php

/**
 * PluginPageContentAudioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageContentAudioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageContentAudioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageContentAudio');
    }
}